// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MuniDbContext))]
    partial class MuniDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Deleted")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = 0,
                            Description = "Atiende trámites generales",
                            Name = "Oficina Martin Fierro"
                        },
                        new
                        {
                            Id = 2,
                            Deleted = 0,
                            Description = "Atiende temas de género",
                            Name = "Oficina Gender"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Citizen", b =>
                {
                    b.Property<int>("DNI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DNI"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CreatedByOperatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DNI");

                    b.HasIndex("CreatedByOperatorId");

                    b.ToTable("Citizens");

                    b.HasData(
                        new
                        {
                            DNI = 46502865,
                            Adress = "Calle Falsa 123",
                            Email = "micaela@example.com",
                            LastName = "Ortigoza",
                            Name = "Micaela",
                            Phone = "3416897542"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Incidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<int?>("CitizenId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Deleted")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IncidenceType")
                        .HasColumnType("integer");

                    b.Property<int>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("OperatorId");

                    b.ToTable("Incidences");
                });

            modelBuilder.Entity("Domain.Entities.Operator", b =>
                {
                    b.Property<int>("NLegajo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NLegajo"));

                    b.Property<int>("DNI")
                        .HasColumnType("integer");

                    b.Property<int>("Deleted")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("NLegajo");

                    b.ToTable("Operators");

                    b.HasData(
                        new
                        {
                            NLegajo = 9999,
                            DNI = 111,
                            Deleted = 0,
                            Email = "admin@munitrack.com",
                            LastName = "General",
                            Name = "Admin",
                            Password = "adminpassword",
                            Phone = "12345678",
                            Position = 2
                        },
                        new
                        {
                            NLegajo = 459850,
                            DNI = 46502865,
                            Deleted = 0,
                            Email = "micaela@example.com",
                            LastName = "Ortigoza",
                            Name = "Micaela",
                            Password = "123abc123",
                            Phone = "3416897542",
                            Position = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Citizen", b =>
                {
                    b.HasOne("Domain.Entities.Operator", null)
                        .WithMany("Citizens")
                        .HasForeignKey("CreatedByOperatorId");
                });

            modelBuilder.Entity("Domain.Entities.Incidence", b =>
                {
                    b.HasOne("Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Citizen", null)
                        .WithMany("Incidences")
                        .HasForeignKey("CitizenId");

                    b.HasOne("Domain.Entities.Operator", "Operator")
                        .WithMany("Incidences")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Domain.Entities.Citizen", b =>
                {
                    b.Navigation("Incidences");
                });

            modelBuilder.Entity("Domain.Entities.Operator", b =>
                {
                    b.Navigation("Citizens");

                    b.Navigation("Incidences");
                });
#pragma warning restore 612, 618
        }
    }
}
